### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by hkgangwar** [terencezl/pydass_vasp#1]
Hey, 
I am trying to install your module using the following commond
pip install git+https://github.com/terencezl/pydass_vasp
and I am getting following error:

error: package directory 'pydass_vasp/poscar' does not exist
 Can you help to debug this. 

Thanks

**Comment by terencezl** [comment]
Hello. Sorry, the package has been through some code refactoring lately. It’s been fixed.

Terence

**Comment by hkgangwar** [comment]
Thanks, 
I was able to install successfully after the update. However, I am facing another issue while trying to plot band structure.   

ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by terencezl** [comment]
Could you send me the EIGENVAL file, or vasprun.xml file, or if possible, all the not-too-large run input and output files? I’ll try to debug it.

Terence

**Comment by hkgangwar** [comment]
Hey,
Files are attached. really appreciate your time.

**Comment by terencezl** [comment]
Sorry. The attachment does not seem to be there… Re-upload?

Terence

**Comment by hkgangwar** [comment]
Thanks, It works fine after updating the ipython.config file. 
However, I am facing another problem now. How does it read KPOINTS and their label? For me it just writes "k" in the xaxis label. Dict output for Kpoints is 
'reciprocal_point_labels': ['k', 'points along high symmetry lines'],
 'reciprocal_point_locations': array([ 0.        ,  0.70710678,  1.45246426,  1.68817124])}

**Comment by terencezl** [comment]
Sorry I did not really say too much on the format, but KPOINTS should have something of ‘K-G-X,F-Z’ in the first line.

But that should not be a problem, as you can use the ‘reciprocal_point_labels’ argument of get_bs()

Terence
